### ISSUE TITLE
GooglePay doesn't work, getting JS Error: Cannot read properties of undefined

### ISSUE THREAD

**Issue by plumrocket** [justinbeaty/module-gene-braintree#4]
Hello Justin, 

Thanks for updating the Braintree extension! We have installed it on OpenMage and tried enabling Google Pay, but always get error messages. 

Here is screenshots: 
![image](https://user-images.githubusercontent.com/4431548/143488838-73d21e37-8bc5-48c9-9c93-e5c6a756c061.png)

![image](https://user-images.githubusercontent.com/4431548/143489549-5dd0bc4b-555b-445f-a2a8-dd612cb397ed.png)

![image](https://user-images.githubusercontent.com/4431548/143489824-1acdbdc7-a27c-420a-b51e-06809cc8a155.png)

Openmage version: 20.0.13

Error Message: 
> TypeError: Cannot read properties of undefined (reading 'submitCheckout')
>     at vzero-googlepay.min.js?v=1629405722:formatted:96

```
      o.loadPaymentData(t).then(function(t) {
          return t,
          n.parseResponse(t)
      }).then(function(t) {
          $("googlepay-payment-nonce").value = t.nonce,
          this.vzero.integration.submitCheckout()
      }
      .bind(this)).catch(function(t) {
          console.error(t)
      })
```

Do you have any idea what could be wrong? Thanks!

**Comment by justinbeaty** [comment]
Hi @plumrocket,

I haven’t used Google Pay, but the first thing I would check is if the original Gene extension also throws this error or not.

You can get the original code from the very first commit in this repo, or flyingmana has shared it once on the OpenMage Discord. There is also an older version in the OpenMage module fostering repos.

I did not change any of the JS in the module, because I’m actually using OpenMage as a headless cart with a Vue frontend, so I use the latest Braintree JS lib there. So technically I haven’t tested this repo with the stock frontend; the main changes I made were updating the Braintree PHP SDK.

I’m away from my computer today, but I’ll look at the error more closely this weekend.

**Comment by plumrocket** [comment]
Hi @justinbeaty. Thanks for a quick response :)

Ok, I guess we will try to debug a little more tomorrow. If you get a chance to look at it too, we will appreciate any help. 

Happy Holidays!
Alex

**Comment by justinbeaty** [comment]
@plumrocket I did some light digging in the JS source code of this module, and one possible issue might be if you have the credit card payment method turned off. I am not positive that is the problem, but I figured I'd ask before digging any further.

**Comment by plumrocket** [comment]
Hey Justin! 
That was an excellent hint! I just tried enabling the credit card payments in the backend, and it worked like a charm :)! Thanks a lot for your help!
Alex

**Comment by justinbeaty** [comment]
@plumrocket Excellent! I'm not sure why it's required, but I noticed that the `this.vzero.integration` object only is initialized when the Hosted Fields form is there, so it was just a guess!

Glad you got it working.

**Comment by KeenEthika** [comment]
> Hey Justin! That was an excellent hint! I just tried enabling the credit card payments in the backend, and it worked like a charm :)! Thanks a lot for your help! Alex

How and where did you turn on the "Credit Card Payment"? Do you remember?

**Comment by justinbeaty** [comment]
@KeenEthika It is at:

System > Configuration > Payment Methods Braintree Payments - Credit Card

You must set Enabled to Yes.
